version: "3"
services:
    instancer:
        build: .
        privileged: true
        environment:
            - "CHALL_NUM_SERVERS=10"
            - "POW_DIFFICULTY=1"
            - "CHALL_INTERNAL_PORT=8000"
            - "CHALL_TIMEOUT=10"

        network_mode: host
